/**
 * Documentation Manager — Web App
 * Main application logic, ported from the Electron renderer/app.js.
 * All window.electronAPI.* calls replaced with FileSystemAPI (fs.js).
 */

import * as FileSystemAPI from './fs.js';
import { exportDocument } from './export.js';
import { previewDocument } from './preview.js';

// ─── Application State ───────────────────────────────────────────────────────

const AppState = {
    currentProjectName: null,
    data: {
        theme: {
            colorBackground: '#f8f9fa',
            colorHighlight: '#1b78aa',
            colorLowLight: '#6c757d',
            colorTitleText: '#212529',
            colorSubTitleText: '#495057',
            colorBodyText: '#6c757d',
            colorCallout: '#0056b3'
        },
        homeContent: {
            introText: 'Welcome to AQUAS Blue Documentation.'
        },
        documents: []
    },
    currentDocument: null,
    currentSection: null,
    editingSectionIndex: -1
};

// ─── Initialize ───────────────────────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', () => {
    checkBrowserCompatibility();
    initializeEventListeners();
    initializeApp();
});

function checkBrowserCompatibility() {
    if (!FileSystemAPI.isSupported()) {
        document.getElementById('compat-banner').style.display = 'block';
        document.getElementById('open-folder-btn').disabled = true;
        document.getElementById('open-folder-btn').textContent = 'Not supported in this browser';
    }
}

async function initializeApp() {
    if (!FileSystemAPI.isConfigured()) {
        showOpenFolderScreen();
    } else {
        await checkForExistingProjects();
    }
}

// ─── Open Folder Screen ──────────────────────────────────────────────────────

function showOpenFolderScreen() {
    document.getElementById('open-folder-screen').style.display = 'flex';
}

function hideOpenFolderScreen() {
    document.getElementById('open-folder-screen').style.display = 'none';
}

async function handleOpenFolder() {
    const result = await FileSystemAPI.openFolder();
    if (result.success) {
        hideOpenFolderScreen();
        await checkForExistingProjects();
    } else if (!result.cancelled) {
        showToast('Failed to open folder: ' + result.error, 'error');
    }
}

// ─── Event Listeners ─────────────────────────────────────────────────────────

function initializeEventListeners() {
    document.getElementById('open-folder-btn').addEventListener('click', handleOpenFolder);

    // Header actions
    document.getElementById('switch-project-btn').addEventListener('click', showProjectModal);
    document.getElementById('import-btn').addEventListener('click', importExternalJSON);
    document.getElementById('export-btn').addEventListener('click', handleExportDocument);

    // Project modal
    document.getElementById('close-project-modal').addEventListener('click', () => {
        if (AppState.currentProjectName) {
            closeProjectModal();
        } else {
            closeProjectModal();
            showOpenFolderScreen();
        }
    });
    document.getElementById('create-project-btn').addEventListener('click', createNewProject);

    // Sidebar
    document.getElementById('add-document-btn').addEventListener('click', addNewDocument);

    // Document editor
    document.getElementById('add-section-btn').addEventListener('click', () => openSectionModal());
    document.getElementById('preview-document-btn').addEventListener('click', handlePreviewDocument);
    document.getElementById('save-document-btn').addEventListener('click', saveCurrentDocument);
    document.getElementById('delete-document-btn').addEventListener('click', deleteCurrentDocument);

    // Card image selector
    document.getElementById('select-card-image-btn').addEventListener('click', selectCardImage);

    // Delete confirmation modal
    document.getElementById('delete-confirm-btn').addEventListener('click', confirmDeleteDocument);
    document.getElementById('delete-cancel-btn').addEventListener('click', () => {
        document.getElementById('delete-confirm-modal').style.display = 'none';
    });

    // Section modal
    document.getElementById('close-modal').addEventListener('click', closeSectionModal);
    document.getElementById('cancel-section-btn').addEventListener('click', closeSectionModal);
    document.getElementById('save-section-btn').addEventListener('click', saveSection);
    document.getElementById('select-section-image-btn').addEventListener('click', selectSectionImage);

    // Document ID auto-generation
    document.getElementById('doc-title').addEventListener('blur', autoGenerateDocId);
}

// ─── Project Management ───────────────────────────────────────────────────────

async function checkForExistingProjects() {
    const result = await FileSystemAPI.listProjects();
    if (!result.success) {
        showToast('Failed to check for projects: ' + result.error, 'error');
        return;
    }
    showProjectModal();
}

async function showProjectModal() {
    const result = await FileSystemAPI.listProjects();
    if (!result.success) {
        showToast('Failed to load projects: ' + result.error, 'error');
        return;
    }

    const projectsList = document.getElementById('existing-projects-list');

    if (result.projects.length === 0) {
        projectsList.innerHTML = '<p class="empty-state">No existing projects found.</p>';
    } else {
        projectsList.innerHTML = '';
        result.projects.forEach(projectName => {
            const item = document.createElement('div');
            item.className = 'project-list-item';
            item.innerHTML = `
                <span class="project-list-item-name">${projectName}</span>
                <span>→</span>
            `;
            item.addEventListener('click', () => openProject(projectName));
            projectsList.appendChild(item);
        });
    }

    document.getElementById('project-modal').style.display = 'flex';
}

function closeProjectModal() {
    document.getElementById('project-modal').style.display = 'none';
    document.getElementById('new-project-name').value = '';
}

async function createNewProject() {
    const projectName = document.getElementById('new-project-name').value.trim();
    if (!projectName) {
        showToast('Please enter a project name', 'error');
        return;
    }

    const result = await FileSystemAPI.createProject(projectName);
    if (!result.success) {
        showToast('Failed to create project: ' + result.error, 'error');
        return;
    }

    showToast('Project created successfully!', 'success');
    await openProject(projectName);
    closeProjectModal();
}

async function openProject(projectName) {
    const result = await FileSystemAPI.loadProject(projectName);
    if (!result.success) {
        showToast('Failed to load project: ' + result.error, 'error');
        return;
    }

    AppState.currentProjectName = projectName;
    AppState.data = result.data;
    AppState.currentDocument = null;

    updateProjectName();
    renderDocumentsList();
    renderDocumentEditor();
    closeProjectModal();

    showToast('Project loaded: ' + projectName, 'success');
}

function updateProjectName() {
    const el = document.getElementById('current-project-name');
    el.textContent = AppState.currentProjectName || 'No Project';
}

async function saveProjectData() {
    if (!AppState.currentProjectName) {
        showToast('No project loaded', 'error');
        return false;
    }

    const result = await FileSystemAPI.saveProject(AppState.currentProjectName, AppState.data);
    if (!result.success) {
        showToast('Failed to save project: ' + result.error, 'error');
        return false;
    }

    return true;
}

// ─── Export ───────────────────────────────────────────────────────────────────

async function handleExportDocument() {
    if (!AppState.currentProjectName || !AppState.currentDocument) {
        showToast('Please open a document to export', 'error');
        return;
    }

    await saveProjectData();

    try {
        showToast('Building export ZIP...', 'info');
        await exportDocument(
            AppState.currentProjectName,
            AppState.currentDocument,
            AppState.data.theme
        );
        showToast(`Exported ${AppState.currentDocument.id}.zip successfully!`, 'success');
    } catch (err) {
        showToast('Export failed: ' + err.message, 'error');
    }
}

// ─── Import ───────────────────────────────────────────────────────────────────

async function importExternalJSON() {
    if (!AppState.currentProjectName) {
        showToast('Please open or create a project first', 'error');
        return;
    }

    const result = await FileSystemAPI.selectDirectory();
    if (!result.success) return;

    const bundleHandle = result.handle;

    // Validate bundle structure
    const validation = await validateDocumentBundle(bundleHandle);
    if (!validation.valid) {
        showToast('Invalid bundle: ' + validation.error, 'error');
        return;
    }

    // Load data.json from bundle
    const jsonResult = await FileSystemAPI.readExternalJSON(bundleHandle, ['data.json']);
    if (!jsonResult.success) {
        showToast('Failed to load data.json: ' + jsonResult.error, 'error');
        return;
    }

    const bundleData = jsonResult.data;
    let documentToImport;

    if (bundleData.documents && Array.isArray(bundleData.documents)) {
        if (bundleData.documents.length === 0) {
            showToast('No documents found in bundle', 'error');
            return;
        }
        documentToImport = bundleData.documents[0];
    } else if (bundleData.id && bundleData.title && bundleData.sections) {
        documentToImport = bundleData;
    } else {
        showToast('Invalid bundle format', 'error');
        return;
    }

    const originalId = documentToImport.id;

    // Verify document ID matches image folder
    if (validation.imageFolder !== originalId) {
        const shouldContinue = confirm(
            `Warning: Document ID "${originalId}" doesn't match image folder "${validation.imageFolder}".\n\n` +
            `The document ID will be corrected to match the image folder.\n\nContinue?`
        );
        if (!shouldContinue) return;
        documentToImport.id = validation.imageFolder;
    }

    // Handle duplicates
    const duplicate = AppState.data.documents.find(doc =>
        doc.id === documentToImport.id || doc.title === documentToImport.title
    );

    if (duplicate) {
        const action = await promptDuplicateAction(documentToImport, duplicate);
        if (action === 'cancel') {
            showToast('Import cancelled', 'info');
            return;
        } else if (action === 'overwrite') {
            const index = AppState.data.documents.findIndex(doc => doc.id === duplicate.id);
            AppState.data.documents.splice(index, 1);
        } else if (action === 'rename') {
            const newId = prompt('Enter a new document ID:', documentToImport.id + '-copy');
            if (!newId || !newId.trim()) {
                showToast('Import cancelled - no ID provided', 'info');
                return;
            }
            const sanitizedId = newId.trim().toLowerCase()
                .replace(/[^a-z0-9\s-]/g, '')
                .replace(/\s+/g, '-');

            if (AppState.data.documents.find(doc => doc.id === sanitizedId)) {
                showToast('A document with this ID already exists', 'error');
                return;
            }

            documentToImport.id = sanitizedId;
            if (documentToImport.cardImage) {
                documentToImport.cardImage = `images/${sanitizedId}/${documentToImport.cardImage.split('/').pop()}`;
            }
            documentToImport.sections.forEach(section => {
                if (section.sectionImage && section.sectionImage.trim()) {
                    section.sectionImage = `images/${sanitizedId}/${section.sectionImage.split('/').pop()}`;
                }
            });
            validation.imageFolder = sanitizedId;
        }
    }

    // Fix image paths to project format
    documentToImport = fixDocumentImagePaths(documentToImport);

    // Find and copy the images directory from the bundle
    let sourceImgHandle = null;
    try {
        // Try bundle/images/originalId/
        const imagesDir = await bundleHandle.getDirectoryHandle('images');
        sourceImgHandle = await imagesDir.getDirectoryHandle(originalId);
    } catch {
        try {
            // Try bundle/originalId/ directly
            sourceImgHandle = await bundleHandle.getDirectoryHandle(originalId);
        } catch {
            // No images found — that's okay
        }
    }

    if (sourceImgHandle) {
        const copyResult = await FileSystemAPI.copyExternalDirectoryToProject(
            AppState.currentProjectName,
            sourceImgHandle,
            `images/${documentToImport.id}`
        );
        if (!copyResult.success) {
            showToast('Failed to copy images: ' + copyResult.error, 'error');
            return;
        }
    }

    AppState.data.documents.push(documentToImport);
    const saved = await saveProjectData();
    if (saved) {
        renderDocumentsList();
        showToast(`Document "${documentToImport.title}" imported successfully!`, 'success');
    }
}

async function validateDocumentBundle(bundleHandle) {
    // Check for data.json
    try {
        await bundleHandle.getFileHandle('data.json');
    } catch {
        return { valid: false, error: 'data.json not found in bundle folder' };
    }

    // Scan for image folder
    let imageFolder = null;
    let imagesParentFolder = null;

    try {
        const imagesDir = await bundleHandle.getDirectoryHandle('images');
        imagesParentFolder = 'images';
        for await (const [name, entry] of imagesDir.entries()) {
            if (entry.kind === 'directory') {
                imageFolder = name;
                break;
            }
        }
    } catch {
        // No images/ folder — look for direct doc folder
        for await (const [name, entry] of bundleHandle.entries()) {
            if (entry.kind === 'directory' && name !== 'data' && name !== 'assets') {
                imageFolder = name;
                break;
            }
        }
    }

    if (!imageFolder) {
        return { valid: false, error: 'No image folder found in bundle' };
    }

    return { valid: true, imageFolder, imagesParentFolder };
}

function fixDocumentImagePaths(doc) {
    if (doc.cardImage) {
        const filename = doc.cardImage.split('/').pop();
        doc.cardImage = `images/${doc.id}/${filename}`;
    }
    doc.sections.forEach(section => {
        if (section.sectionImage && section.sectionImage.trim()) {
            const filename = section.sectionImage.split('/').pop();
            section.sectionImage = `images/${doc.id}/${filename}`;
        }
    });
    return doc;
}

async function promptDuplicateAction(newDoc, existingDoc) {
    const message =
        `A document with ${existingDoc.id === newDoc.id ? 'ID' : 'title'} ` +
        `"${existingDoc.id === newDoc.id ? existingDoc.id : existingDoc.title}" already exists.\n\n` +
        `Existing: "${existingDoc.title}" (v${existingDoc.version})\n` +
        `Importing: "${newDoc.title}" (v${newDoc.version})\n\n` +
        `Enter: "overwrite", "rename", or "cancel"`;
    const action = prompt(message, 'cancel');
    return action ? action.toLowerCase().trim() : 'cancel';
}

// ─── Document List ────────────────────────────────────────────────────────────

function renderDocumentsList() {
    const container = document.getElementById('documents-list');

    if (AppState.data.documents.length === 0) {
        container.innerHTML = '<p class="empty-state">No documents yet. Click ➕ to add one.</p>';
        return;
    }

    container.innerHTML = '';
    AppState.data.documents.forEach((doc, index) => {
        const item = document.createElement('div');
        item.className = 'document-item';
        if (AppState.currentDocument && AppState.currentDocument.id === doc.id) {
            item.classList.add('active');
        }
        item.innerHTML = `
            <div class="document-item-title">${doc.title}</div>
            <div class="document-item-meta">v${doc.version} • ${doc.sections.length} sections</div>
        `;
        item.addEventListener('click', () => loadDocument(index));
        container.appendChild(item);
    });
}

// ─── Document Editing ─────────────────────────────────────────────────────────

async function addNewDocument() {
    if (!AppState.currentProjectName) {
        showToast('Please open or create a project first', 'error');
        return;
    }

    const newDoc = {
        id: 'new-document-' + Date.now(),
        title: 'New Document',
        version: '1.0',
        lastUpdated: new Date().toISOString().split('T')[0],
        description: '',
        cardImage: '',
        sections: []
    };

    AppState.data.documents.push(newDoc);
    AppState.currentDocument = newDoc;

    await saveProjectData();
    renderDocumentsList();
    renderDocumentEditor();
    showToast('New document created', 'success');
}

function loadDocument(index) {
    AppState.currentDocument = AppState.data.documents[index];
    renderDocumentsList();
    renderDocumentEditor();
}

function renderDocumentEditor() {
    const welcomeScreen = document.getElementById('welcome-screen');
    const editorScreen = document.getElementById('document-editor');
    const toolbar = document.getElementById('doc-toolbar');

    if (!AppState.currentDocument) {
        welcomeScreen.style.display = 'block';
        editorScreen.style.display = 'none';
        toolbar.style.display = 'none';
        return;
    }

    welcomeScreen.style.display = 'none';
    editorScreen.style.display = 'block';
    toolbar.style.display = 'flex';

    const doc = AppState.currentDocument;
    document.getElementById('doc-title').value = doc.title;
    document.getElementById('doc-id').value = doc.id;
    document.getElementById('doc-version').value = doc.version;
    document.getElementById('doc-updated').value = doc.lastUpdated;
    document.getElementById('doc-description').value = doc.description;
    document.getElementById('doc-card-image').value = doc.cardImage;

    renderSections();
}

function renderSections() {
    const container = document.getElementById('sections-container');

    if (!AppState.currentDocument.sections || AppState.currentDocument.sections.length === 0) {
        container.innerHTML = '<p class="empty-state">No sections yet. Click "Add Section" to create one.</p>';
        return;
    }

    container.innerHTML = '';
    AppState.currentDocument.sections.forEach((section, index) => {
        const hasSubtitle = section.sectionSubTitle && section.sectionSubTitle.trim();
        const hasImage = section.sectionImage && section.sectionImage.trim();
        const bodyPreview = section.sectionBody.length > 150
            ? section.sectionBody.substring(0, 150) + '...'
            : section.sectionBody;

        const card = document.createElement('div');
        card.className = 'section-card';
        card.innerHTML = `
            <div class="section-card-header">
                <div>
                    <div class="section-card-title">${index + 1}. ${section.sectionTitle}</div>
                    ${hasSubtitle ? `<div class="section-card-subtitle">${section.sectionSubTitle}</div>` : ''}
                </div>
                <div class="section-card-actions">
                    <button class="btn-move-up" data-index="${index}" ${index === 0 ? 'disabled' : ''} title="Move up">⬆️</button>
                    <button class="btn-move-down" data-index="${index}" ${index === AppState.currentDocument.sections.length - 1 ? 'disabled' : ''} title="Move down">⬇️</button>
                    <button class="btn-edit" data-index="${index}" title="Edit">✏️</button>
                    <button class="btn-delete" data-index="${index}" title="Delete">🗑️</button>
                </div>
            </div>
            <div class="section-card-body">${bodyPreview}</div>
            ${hasImage ? `<div style="margin-top:0.5rem;font-size:0.85rem;color:var(--color-text-secondary);">📷 ${section.sectionImage}</div>` : ''}
        `;

        const moveUpBtn = card.querySelector('.btn-move-up');
        const moveDownBtn = card.querySelector('.btn-move-down');
        if (moveUpBtn && !moveUpBtn.disabled) moveUpBtn.addEventListener('click', () => moveSection(index, -1));
        if (moveDownBtn && !moveDownBtn.disabled) moveDownBtn.addEventListener('click', () => moveSection(index, 1));
        card.querySelector('.btn-edit').addEventListener('click', () => editSection(index));
        card.querySelector('.btn-delete').addEventListener('click', () => deleteSection(index));

        container.appendChild(card);
    });
}

async function moveSection(index, direction) {
    const sections = AppState.currentDocument.sections;
    const newIndex = index + direction;
    if (newIndex < 0 || newIndex >= sections.length) return;
    [sections[index], sections[newIndex]] = [sections[newIndex], sections[index]];
    await saveProjectData();
    renderSections();
    showToast('Section moved', 'success');
}

function editSection(index) {
    AppState.editingSectionIndex = index;
    const section = AppState.currentDocument.sections[index];
    document.getElementById('modal-title').textContent = 'Edit Section';
    document.getElementById('section-title').value = section.sectionTitle;
    document.getElementById('section-subtitle').value = section.sectionSubTitle;
    document.getElementById('section-body').value = section.sectionBody;
    document.getElementById('section-image').value = section.sectionImage;
    document.getElementById('section-modal').style.display = 'flex';
}

async function deleteSection(index) {
    if (confirm('Are you sure you want to delete this section?')) {
        AppState.currentDocument.sections.splice(index, 1);
        await saveProjectData();
        renderSections();
        showToast('Section deleted', 'success');
    }
}

// ─── Section Modal ────────────────────────────────────────────────────────────

function openSectionModal(index = -1) {
    if (index === -1) {
        document.getElementById('modal-title').textContent = 'Add Section';
        document.getElementById('section-title').value = '';
        document.getElementById('section-subtitle').value = '';
        document.getElementById('section-body').value = '';
        document.getElementById('section-image').value = '';
        AppState.editingSectionIndex = -1;
    }
    document.getElementById('section-modal').style.display = 'flex';
}

function closeSectionModal() {
    document.getElementById('section-modal').style.display = 'none';
    AppState.editingSectionIndex = -1;
}

async function saveSection() {
    const title = document.getElementById('section-title').value.trim();
    const subtitle = document.getElementById('section-subtitle').value.trim();
    const body = document.getElementById('section-body').value.trim();
    const image = document.getElementById('section-image').value.trim();

    if (!title || !body) {
        showToast('Section title and body are required', 'error');
        return;
    }

    const section = {
        sectionTitle: title,
        sectionSubTitle: subtitle,
        sectionBody: body,
        sectionImage: image
    };

    if (AppState.editingSectionIndex >= 0) {
        AppState.currentDocument.sections[AppState.editingSectionIndex] = section;
        showToast('Section updated', 'success');
    } else {
        AppState.currentDocument.sections.push(section);
        showToast('Section added', 'success');
    }

    await saveProjectData();
    renderSections();
    closeSectionModal();
}

// ─── Document Save/Delete ─────────────────────────────────────────────────────

async function saveCurrentDocument() {
    const title = document.getElementById('doc-title').value.trim();
    const id = document.getElementById('doc-id').value.trim();
    const version = document.getElementById('doc-version').value.trim();
    const updated = document.getElementById('doc-updated').value;
    const description = document.getElementById('doc-description').value.trim();
    const cardImage = document.getElementById('doc-card-image').value.trim();

    if (!title || !id) {
        showToast('Document title and ID are required', 'error');
        return;
    }

    const duplicateId = AppState.data.documents.find(doc =>
        doc.id === id && doc !== AppState.currentDocument
    );
    if (duplicateId) {
        showToast('A document with this ID already exists', 'error');
        return;
    }

    AppState.currentDocument.title = title;
    AppState.currentDocument.id = id;
    AppState.currentDocument.version = version;
    AppState.currentDocument.lastUpdated = updated;
    AppState.currentDocument.description = description;
    AppState.currentDocument.cardImage = cardImage;

    const saved = await saveProjectData();
    if (saved) {
        renderDocumentsList();
        showToast('Document saved', 'success');
    }
}

function deleteCurrentDocument() {
    if (!AppState.currentDocument) return;
    document.getElementById('delete-confirm-doc-name').textContent = AppState.currentDocument.title || 'this document';
    document.getElementById('delete-confirm-modal').style.display = 'flex';
}

async function confirmDeleteDocument() {
    document.getElementById('delete-confirm-modal').style.display = 'none';
    const index = AppState.data.documents.findIndex(doc => doc === AppState.currentDocument);
    if (index > -1) {
        AppState.data.documents.splice(index, 1);
        AppState.currentDocument = null;
        await saveProjectData();
        renderDocumentsList();
        renderDocumentEditor();
        showToast('Document deleted', 'success');
    }
}

function autoGenerateDocId() {
    const title = document.getElementById('doc-title').value.trim();
    const currentId = document.getElementById('doc-id').value.trim();
    if (!currentId || currentId.startsWith('new-document-')) {
        document.getElementById('doc-id').value = title
            .toLowerCase()
            .replace(/[^a-z0-9\s-]/g, '')
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-')
            .replace(/^-|-$/g, '');
    }
}

// ─── Image Selection ──────────────────────────────────────────────────────────

async function selectCardImage() {
    if (!AppState.currentProjectName || !AppState.currentDocument) {
        showToast('Please save the document first', 'error');
        return;
    }

    const result = await FileSystemAPI.selectFile({
        filters: [{ name: 'Images', extensions: ['png', 'jpg', 'jpeg', 'svg', 'gif'] }]
    });

    if (result.success) {
        const docId = document.getElementById('doc-id').value.trim() || AppState.currentDocument.id;
        const relativePath = `images/${docId}/${result.name}`;

        const copyResult = await FileSystemAPI.copyFileToProject(
            AppState.currentProjectName, result.file, relativePath
        );

        if (copyResult.success) {
            document.getElementById('doc-card-image').value = relativePath;
            showToast('Image copied to project!', 'success');
        } else {
            showToast('Failed to copy image: ' + copyResult.error, 'error');
        }
    }
}

async function selectSectionImage() {
    if (!AppState.currentProjectName || !AppState.currentDocument) {
        showToast('Please save the document first', 'error');
        return;
    }

    const result = await FileSystemAPI.selectFile({
        filters: [{ name: 'Images', extensions: ['png', 'jpg', 'jpeg', 'svg', 'gif'] }]
    });

    if (result.success) {
        const docId = AppState.currentDocument.id;
        const relativePath = `images/${docId}/${result.name}`;

        const copyResult = await FileSystemAPI.copyFileToProject(
            AppState.currentProjectName, result.file, relativePath
        );

        if (copyResult.success) {
            document.getElementById('section-image').value = relativePath;
            showToast('Image copied to project!', 'success');
        } else {
            showToast('Failed to copy image: ' + copyResult.error, 'error');
        }
    }
}

// ─── Preview ──────────────────────────────────────────────────────────────────

async function handlePreviewDocument() {
    if (!AppState.currentProjectName || !AppState.currentDocument) {
        showToast('No document loaded', 'error');
        return;
    }
    if (AppState.currentDocument.sections.length === 0) {
        showToast('Document has no sections to preview', 'error');
        return;
    }

    showToast('Generating preview...', 'info');
    try {
        await previewDocument(
            AppState.currentProjectName,
            AppState.currentDocument,
            AppState.data.theme
        );
        showToast('Preview opened in new tab!', 'success');
    } catch (err) {
        showToast('Preview failed: ' + err.message, 'error');
    }
}

// ─── Toast Notification ───────────────────────────────────────────────────────

function showToast(message, type = 'info') {
    const toast = document.getElementById('toast');
    toast.textContent = message;
    toast.className = 'toast ' + type;
    toast.style.display = 'block';
    setTimeout(() => { toast.style.display = 'none'; }, 3000);
}
