// Application State
const AppState = {
    currentProjectName: null,
    data: {
        theme: {
            colorBackground: "#f8f9fa",
            colorHighlight: "#1b78aa",
            colorLowLight: "#6c757d",
            colorTitleText: "#212529",
            colorSubTitleText: "#495057",
            colorBodyText: "#6c757d",
            colorCallout: "#0056b3"
        },
        homeContent: {
            introText: "Welcome to AQUAS Blue Documentation. Browse our comprehensive guides to get started quickly or explore the full capabilities of the AQUAS Blue platform. Select a guide below to begin your journey."
        },
        documents: []
    },
    currentDocument: null,
    currentSection: null,
    editingSectionIndex: -1
};

// Initialize App
document.addEventListener('DOMContentLoaded', async () => {
    initializeEventListeners();
    await initializeApp();
});

// Initialize Application
async function initializeApp() {
    // Check if storage location is configured
    const storageCheck = await window.electronAPI.checkStorageConfigured();
    
    if (!storageCheck.isConfigured) {
        // First launch - ask user to select storage location
        await promptForStorageLocation();
    }
    
    // Now proceed with normal startup
    await checkForExistingProjects();
}

// Prompt user to select storage location
async function promptForStorageLocation() {
    const message = `Welcome to Documentation Manager!\n\nPlease select where you'd like to store your projects.\n\nA folder called "Document Manager/Projects" will be created at your chosen location.`;
    
    if (confirm(message)) {
        const result = await window.electronAPI.setStorageLocation();
        
        if (result.success) {
            showToast(`Projects will be stored at: ${result.path}/Document Manager/Projects`, 'success');
        } else if (result.cancelled) {
            alert('You must select a storage location to use the app. The app will now close.');
            window.close();
        }
    } else {
        alert('You must select a storage location to use the app. The app will now close.');
        window.close();
    }
}

// Event Listeners
function initializeEventListeners() {
    // Header actions
    document.getElementById('switch-project-btn').addEventListener('click', showProjectModal);
    document.getElementById('import-btn').addEventListener('click', importExternalJSON);
    document.getElementById('export-btn').addEventListener('click', exportProject);
    
    // Project modal
    document.getElementById('create-project-btn').addEventListener('click', createNewProject);
    document.getElementById('change-storage-btn').addEventListener('click', changeStorageLocation);
    
    // Sidebar
    document.getElementById('add-document-btn').addEventListener('click', addNewDocument);
    
    // Document editor
    document.getElementById('add-section-btn').addEventListener('click', () => openSectionModal());
    document.getElementById('preview-document-btn').addEventListener('click', previewCurrentDocument);
    document.getElementById('save-document-btn').addEventListener('click', saveCurrentDocument);
    document.getElementById('delete-document-btn').addEventListener('click', deleteCurrentDocument);
    
    // Card image selector
    document.getElementById('select-card-image-btn').addEventListener('click', selectCardImage);
    
    // Section modal
    document.getElementById('close-modal').addEventListener('click', closeSectionModal);
    document.getElementById('cancel-section-btn').addEventListener('click', closeSectionModal);
    document.getElementById('save-section-btn').addEventListener('click', saveSection);
    document.getElementById('select-section-image-btn').addEventListener('click', selectSectionImage);
    
    // Document ID auto-generation
    document.getElementById('doc-title').addEventListener('blur', autoGenerateDocId);
}

// ===== PROJECT MANAGEMENT =====

// Check for existing projects on startup
async function checkForExistingProjects() {
    const result = await window.electronAPI.listProjects();
    
    if (!result.success) {
        showToast('Failed to check for projects: ' + result.error, 'error');
        return;
    }
    
    if (result.projects.length === 0) {
        // No projects exist, show modal to create one
        showProjectModal();
    } else {
        // Projects exist, load the most recent one or show selection
        showProjectModal();
    }
}

// Show project selection modal
async function showProjectModal() {
    // Display current storage location
    const storageCheck = await window.electronAPI.checkStorageConfigured();
    const storageDisplay = document.getElementById('storage-location-display');
    if (storageCheck.isConfigured && storageCheck.path) {
        storageDisplay.textContent = `${storageCheck.path}/Document Manager/Projects`;
    } else {
        storageDisplay.textContent = 'Not configured';
    }
    
    const result = await window.electronAPI.listProjects();
    
    if (!result.success) {
        showToast('Failed to load projects: ' + result.error, 'error');
        return;
    }
    
    const projectsList = document.getElementById('existing-projects-list');
    
    if (result.projects.length === 0) {
        projectsList.innerHTML = '<p class="empty-state">No existing projects found.</p>';
    } else {
        projectsList.innerHTML = '';
        result.projects.forEach(projectName => {
            const item = document.createElement('div');
            item.className = 'project-list-item';
            item.innerHTML = `
                <span class="project-list-item-name">${projectName}</span>
                <span>→</span>
            `;
            item.addEventListener('click', () => openProject(projectName));
            projectsList.appendChild(item);
        });
    }
    
    document.getElementById('project-modal').style.display = 'flex';
}

// Change storage location
async function changeStorageLocation() {
    if (!confirm('Warning: Changing the storage location will not move your existing projects. You will need to manually move the "Document Manager" folder to the new location.\n\nDo you want to continue?')) {
        return;
    }
    
    const result = await window.electronAPI.setStorageLocation();
    
    if (result.success) {
        showToast(`Storage location updated to: ${result.path}`, 'success');
        // Refresh the project modal
        closeProjectModal();
        await showProjectModal();
    } else if (!result.cancelled) {
        showToast('Failed to change storage location', 'error');
    }
}

// Close project modal
function closeProjectModal() {
    document.getElementById('project-modal').style.display = 'none';
    document.getElementById('new-project-name').value = '';
}

// Create new project
async function createNewProject() {
    const projectName = document.getElementById('new-project-name').value.trim();
    
    if (!projectName) {
        showToast('Please enter a project name', 'error');
        return;
    }
    
    const result = await window.electronAPI.createProject(projectName);
    
    if (!result.success) {
        showToast('Failed to create project: ' + result.error, 'error');
        return;
    }
    
    showToast('Project created successfully!', 'success');
    await openProject(projectName);
    closeProjectModal();
}

// Open existing project
async function openProject(projectName) {
    const result = await window.electronAPI.loadProject(projectName);
    
    if (!result.success) {
        showToast('Failed to load project: ' + result.error, 'error');
        return;
    }
    
    AppState.currentProjectName = projectName;
    AppState.data = result.data;
    AppState.currentDocument = null;
    
    updateProjectName();
    renderDocumentsList();
    renderDocumentEditor();
    closeProjectModal();
    
    showToast('Project loaded: ' + projectName, 'success');
}

// Update project name display
function updateProjectName() {
    const projectNameEl = document.getElementById('current-project-name');
    if (AppState.currentProjectName) {
        projectNameEl.textContent = AppState.currentProjectName;
    } else {
        projectNameEl.textContent = 'No Project';
    }
}

// Save current project
async function saveProjectData() {
    if (!AppState.currentProjectName) {
        showToast('No project loaded', 'error');
        return false;
    }
    
    const result = await window.electronAPI.saveProject(AppState.currentProjectName, AppState.data);
    
    if (!result.success) {
        showToast('Failed to save project: ' + result.error, 'error');
        return false;
    }
    
    return true;
}

// Import Document Bundle
async function importExternalJSON() {
    if (!AppState.currentProjectName) {
        showToast('Please open or create a project first', 'error');
        return;
    }
    
    // Select the bundle folder
    const result = await window.electronAPI.selectDirectory({
        title: 'Select Document Bundle Folder',
        message: 'Choose a folder containing data.json and images',
        buttonLabel: 'Import'
    });
    
    if (!result.success) return;
    
    const bundlePath = result.path;
    
    // Validate bundle structure
    const validation = await validateDocumentBundle(bundlePath);
    
    if (!validation.valid) {
        showToast('Invalid bundle: ' + validation.error, 'error');
        return;
    }
    
    // Load and process the document
    const jsonPath = bundlePath + '/data.json';
    const loadResult = await window.electronAPI.loadJSON(jsonPath);
    
    if (!loadResult.success) {
        showToast('Failed to load data.json: ' + loadResult.error, 'error');
        return;
    }
    
    const bundleData = loadResult.data;
    
    // Handle two formats:
    // 1. Full data.json with documents array: { documents: [...] }
    // 2. Single document object: { id: "...", title: "...", ... }
    let documentToImport;
    
    if (bundleData.documents && Array.isArray(bundleData.documents)) {
        // Format 1: Full structure with documents array
        if (bundleData.documents.length === 0) {
            showToast('No documents found in bundle', 'error');
            return;
        }
        documentToImport = bundleData.documents[0];
    } else if (bundleData.id && bundleData.title && bundleData.sections) {
        // Format 2: Direct document object
        documentToImport = bundleData;
    } else {
        showToast('Invalid bundle format: Expected document object or documents array', 'error');
        return;
    }
    
    const originalId = documentToImport.id;
    
    // Verify document ID matches image folder
    if (validation.imageFolder !== originalId) {
        const shouldContinue = confirm(
            `Warning: Document ID "${originalId}" doesn't match image folder "${validation.imageFolder}".\n\n` +
            `The document ID will be corrected to match the image folder.\n\nContinue?`
        );
        
        if (!shouldContinue) return;
        
        // Correct the document ID to match the image folder
        documentToImport.id = validation.imageFolder;
    }
    
    // Check for duplicates
    const duplicate = AppState.data.documents.find(doc => 
        doc.id === documentToImport.id || doc.title === documentToImport.title
    );
    
    if (duplicate) {
        const action = await promptDuplicateAction(documentToImport, duplicate);
        
        if (action === 'cancel') {
            showToast('Import cancelled', 'info');
            return;
        } else if (action === 'overwrite') {
            // Remove the existing document
            const index = AppState.data.documents.findIndex(doc => doc.id === duplicate.id);
            AppState.data.documents.splice(index, 1);
        } else if (action === 'rename') {
            // Prompt for new name
            const newId = prompt('Enter a new document ID:', documentToImport.id + '-copy');
            if (!newId || !newId.trim()) {
                showToast('Import cancelled - no ID provided', 'info');
                return;
            }
            
            const sanitizedId = newId.trim().toLowerCase()
                .replace(/[^a-z0-9\s-]/g, '')
                .replace(/\s+/g, '-');
            
            // Check if new ID already exists
            if (AppState.data.documents.find(doc => doc.id === sanitizedId)) {
                showToast('A document with this ID already exists', 'error');
                return;
            }
            
            // Update document with new ID
            const oldId = documentToImport.id;
            documentToImport.id = sanitizedId;
            
            // Update all image paths (using project format: images/)
            if (documentToImport.cardImage) {
                const filename = documentToImport.cardImage.split('/').pop();
                documentToImport.cardImage = `images/${sanitizedId}/${filename}`;
            }
            
            documentToImport.sections.forEach(section => {
                if (section.sectionImage && section.sectionImage.trim()) {
                    const filename = section.sectionImage.split('/').pop();
                    section.sectionImage = `images/${sanitizedId}/${filename}`;
                }
            });
            
            // We'll copy images to new folder name
            validation.imageFolder = sanitizedId;
        }
    }
    
    // Fix all image paths to match project structure
    documentToImport = fixDocumentImagePaths(documentToImport);
    
    // Copy images to project
    const sourceImagesPath = bundlePath + '/' + (validation.imagesParentFolder ? validation.imagesParentFolder + '/' : '') + originalId;
    const targetImagesPath = `images/${documentToImport.id}`;
    
    const copyResult = await window.electronAPI.copyDirectoryToProject(
        AppState.currentProjectName,
        sourceImagesPath,
        targetImagesPath
    );
    
    if (!copyResult.success) {
        showToast('Failed to copy images: ' + copyResult.error, 'error');
        return;
    }
    
    // Add document to project
    AppState.data.documents.push(documentToImport);
    
    // Save project
    const saved = await saveProjectData();
    
    if (saved) {
        renderDocumentsList();
        showToast(`Document "${documentToImport.title}" imported successfully!`, 'success');
    }
}

// Validate Document Bundle
async function validateDocumentBundle(bundlePath) {
    // Check for data.json
    const dataJsonPath = bundlePath + '/data.json';
    const dataJsonExists = await window.electronAPI.pathExists(dataJsonPath);
    
    if (!dataJsonExists.exists) {
        return { valid: false, error: 'data.json not found in bundle folder' };
    }
    
    // List directory contents
    const contents = await window.electronAPI.listDirectory(bundlePath);
    
    if (!contents.success) {
        return { valid: false, error: 'Failed to read bundle folder contents' };
    }
    
    // Look for images folder or direct document folder
    let imageFolder = null;
    let imagesParentFolder = null;
    
    // Check if there's an "images" folder
    if (contents.directories.includes('images')) {
        imagesParentFolder = 'images';
        const imagesPath = bundlePath + '/images';
        const imagesContents = await window.electronAPI.listDirectory(imagesPath);
        
        if (imagesContents.success && imagesContents.directories.length > 0) {
            imageFolder = imagesContents.directories[0]; // Take first folder as document ID
        }
    } else {
        // Check for direct document ID folder
        const potentialDocFolders = contents.directories.filter(dir => 
            dir !== 'data' && dir !== 'assets'
        );
        
        if (potentialDocFolders.length > 0) {
            imageFolder = potentialDocFolders[0];
        }
    }
    
    if (!imageFolder) {
        return { valid: false, error: 'No image folder found in bundle' };
    }
    
    return { 
        valid: true, 
        imageFolder,
        imagesParentFolder
    };
}

// Fix Document Image Paths (for project structure, not export)
function fixDocumentImagePaths(doc) {
    // Ensure card image path is correct for PROJECT structure: images/[doc-id]/...
    if (doc.cardImage) {
        const filename = doc.cardImage.split('/').pop();
        // Use project-relative path (images/, not assets/images/)
        doc.cardImage = `images/${doc.id}/${filename}`;
    }
    
    // Fix all section image paths for PROJECT structure
    doc.sections.forEach(section => {
        if (section.sectionImage && section.sectionImage.trim()) {
            const filename = section.sectionImage.split('/').pop();
            // Use project-relative path (images/, not assets/images/)
            section.sectionImage = `images/${doc.id}/${filename}`;
        }
        // If empty string, leave it as is
    });
    
    return doc;
}

// Prompt for Duplicate Action
async function promptDuplicateAction(newDoc, existingDoc) {
    const message = `A document with ${existingDoc.id === newDoc.id ? 'ID' : 'title'} "${existingDoc.id === newDoc.id ? existingDoc.id : existingDoc.title}" already exists.\n\n` +
        `Existing: "${existingDoc.title}" (v${existingDoc.version})\n` +
        `Importing: "${newDoc.title}" (v${newDoc.version})\n\n` +
        `What would you like to do?`;
    
    const action = prompt(message + '\n\nEnter: "overwrite", "rename", or "cancel"', 'cancel');
    
    return action ? action.toLowerCase().trim() : 'cancel';
}

// Export Project for Web Deployment
async function exportProject() {
    if (!AppState.currentProjectName) {
        showToast('Please open or create a project first', 'error');
        return;
    }
    
    // First save current state
    await saveProjectData();
    
    // Export the project
    const result = await window.electronAPI.exportProject(AppState.currentProjectName);
    
    if (result.success) {
        showToast('Project exported successfully to: ' + result.path, 'success');
    } else {
        showToast('Failed to export project: ' + result.error, 'error');
    }
}

// Render Documents List
function renderDocumentsList() {
    const container = document.getElementById('documents-list');
    
    if (AppState.data.documents.length === 0) {
        container.innerHTML = '<p class="empty-state">No documents yet. Click ➕ to add one.</p>';
        return;
    }
    
    container.innerHTML = '';
    
    AppState.data.documents.forEach((doc, index) => {
        const item = document.createElement('div');
        item.className = 'document-item';
        if (AppState.currentDocument && AppState.currentDocument.id === doc.id) {
            item.classList.add('active');
        }
        
        item.innerHTML = `
            <div class="document-item-title">${doc.title}</div>
            <div class="document-item-meta">v${doc.version} • ${doc.sections.length} sections</div>
        `;
        
        item.addEventListener('click', () => loadDocument(index));
        container.appendChild(item);
    });
}

// Add New Document
async function addNewDocument() {
    if (!AppState.currentProjectName) {
        showToast('Please open or create a project first', 'error');
        return;
    }
    
    const newDoc = {
        id: "new-document-" + Date.now(),
        title: "New Document",
        version: "1.0",
        lastUpdated: new Date().toISOString().split('T')[0],
        description: "",
        cardImage: "",
        sections: []
    };
    
    AppState.data.documents.push(newDoc);
    AppState.currentDocument = newDoc;
    
    // Auto-save to project
    await saveProjectData();
    
    renderDocumentsList();
    renderDocumentEditor();
    showToast('New document created', 'success');
}

// Load Document
function loadDocument(index) {
    AppState.currentDocument = AppState.data.documents[index];
    renderDocumentsList();
    renderDocumentEditor();
}

// Render Document Editor
function renderDocumentEditor() {
    const welcomeScreen = document.getElementById('welcome-screen');
    const editorScreen = document.getElementById('document-editor');
    
    if (!AppState.currentDocument) {
        welcomeScreen.style.display = 'block';
        editorScreen.style.display = 'none';
        return;
    }
    
    welcomeScreen.style.display = 'none';
    editorScreen.style.display = 'block';
    
    const doc = AppState.currentDocument;
    
    // Populate form fields
    document.getElementById('doc-title').value = doc.title;
    document.getElementById('doc-id').value = doc.id;
    document.getElementById('doc-version').value = doc.version;
    document.getElementById('doc-updated').value = doc.lastUpdated;
    document.getElementById('doc-description').value = doc.description;
    document.getElementById('doc-card-image').value = doc.cardImage;
    
    // Render sections
    renderSections();
}

// Render Sections
function renderSections() {
    const container = document.getElementById('sections-container');
    
    if (!AppState.currentDocument.sections || AppState.currentDocument.sections.length === 0) {
        container.innerHTML = '<p class="empty-state">No sections yet. Click "Add Section" to create one.</p>';
        return;
    }
    
    container.innerHTML = '';
    
    AppState.currentDocument.sections.forEach((section, index) => {
        const card = document.createElement('div');
        card.className = 'section-card';
        
        const hasSubtitle = section.sectionSubTitle && section.sectionSubTitle.trim();
        const hasImage = section.sectionImage && section.sectionImage.trim();
        
        const bodyPreview = section.sectionBody.length > 150 
            ? section.sectionBody.substring(0, 150) + '...' 
            : section.sectionBody;
        
        card.innerHTML = `
            <div class="section-card-header">
                <div>
                    <div class="section-card-title">${index + 1}. ${section.sectionTitle}</div>
                    ${hasSubtitle ? `<div class="section-card-subtitle">${section.sectionSubTitle}</div>` : ''}
                </div>
                <div class="section-card-actions">
                    <button class="btn-move-up" data-index="${index}" ${index === 0 ? 'disabled' : ''} title="Move up">⬆️</button>
                    <button class="btn-move-down" data-index="${index}" ${index === AppState.currentDocument.sections.length - 1 ? 'disabled' : ''} title="Move down">⬇️</button>
                    <button class="btn-edit" data-index="${index}" title="Edit">✏️</button>
                    <button class="btn-delete" data-index="${index}" title="Delete">🗑️</button>
                </div>
            </div>
            <div class="section-card-body">${bodyPreview}</div>
            ${hasImage ? `<div style="margin-top: 0.5rem; font-size: 0.85rem; color: var(--color-text-secondary);">📷 ${section.sectionImage}</div>` : ''}
        `;
        
        // Add event listeners
        const moveUpBtn = card.querySelector('.btn-move-up');
        const moveDownBtn = card.querySelector('.btn-move-down');
        const editBtn = card.querySelector('.btn-edit');
        const deleteBtn = card.querySelector('.btn-delete');
        
        if (moveUpBtn && !moveUpBtn.disabled) {
            moveUpBtn.addEventListener('click', () => moveSection(index, -1));
        }
        if (moveDownBtn && !moveDownBtn.disabled) {
            moveDownBtn.addEventListener('click', () => moveSection(index, 1));
        }
        editBtn.addEventListener('click', () => editSection(index));
        deleteBtn.addEventListener('click', () => deleteSection(index));
        
        container.appendChild(card);
    });
}

// Move Section
async function moveSection(index, direction) {
    const sections = AppState.currentDocument.sections;
    const newIndex = index + direction;
    
    if (newIndex < 0 || newIndex >= sections.length) return;
    
    [sections[index], sections[newIndex]] = [sections[newIndex], sections[index]];
    
    // Auto-save to project
    await saveProjectData();
    
    renderSections();
    showToast('Section moved', 'success');
}

// Edit Section
function editSection(index) {
    AppState.editingSectionIndex = index;
    const section = AppState.currentDocument.sections[index];
    
    document.getElementById('modal-title').textContent = 'Edit Section';
    document.getElementById('section-title').value = section.sectionTitle;
    document.getElementById('section-subtitle').value = section.sectionSubTitle;
    document.getElementById('section-body').value = section.sectionBody;
    document.getElementById('section-image').value = section.sectionImage;
    
    openSectionModal();
}

// Delete Section
async function deleteSection(index) {
    if (confirm('Are you sure you want to delete this section?')) {
        AppState.currentDocument.sections.splice(index, 1);
        
        // Auto-save to project
        await saveProjectData();
        
        renderSections();
        showToast('Section deleted', 'success');
    }
}

// Section Modal
function openSectionModal(index = -1) {
    if (index === -1) {
        // New section
        document.getElementById('modal-title').textContent = 'Add Section';
        document.getElementById('section-title').value = '';
        document.getElementById('section-subtitle').value = '';
        document.getElementById('section-body').value = '';
        document.getElementById('section-image').value = '';
        AppState.editingSectionIndex = -1;
    }
    
    document.getElementById('section-modal').style.display = 'flex';
}

function closeSectionModal() {
    document.getElementById('section-modal').style.display = 'none';
    AppState.editingSectionIndex = -1;
}

async function saveSection() {
    const title = document.getElementById('section-title').value.trim();
    const subtitle = document.getElementById('section-subtitle').value.trim();
    const body = document.getElementById('section-body').value.trim();
    const image = document.getElementById('section-image').value.trim();
    
    if (!title || !body) {
        showToast('Section title and body are required', 'error');
        return;
    }
    
    const section = {
        sectionTitle: title,
        sectionSubTitle: subtitle,
        sectionBody: body,
        sectionImage: image
    };
    
    if (AppState.editingSectionIndex >= 0) {
        // Update existing section
        AppState.currentDocument.sections[AppState.editingSectionIndex] = section;
        showToast('Section updated', 'success');
    } else {
        // Add new section
        AppState.currentDocument.sections.push(section);
        showToast('Section added', 'success');
    }
    
    // Auto-save to project
    await saveProjectData();
    
    renderSections();
    closeSectionModal();
}

// Preview Current Document
async function previewCurrentDocument() {
    if (!AppState.currentProjectName || !AppState.currentDocument) {
        showToast('No document loaded', 'error');
        return;
    }
    
    if (AppState.currentDocument.sections.length === 0) {
        showToast('Document has no sections to preview', 'error');
        return;
    }
    
    showToast('Generating preview...', 'info');
    
    const result = await window.electronAPI.previewDocument(
        AppState.currentProjectName,
        AppState.currentDocument,
        AppState.data.theme
    );
    
    if (result.success) {
        showToast('Preview opened in browser!', 'success');
    } else {
        showToast('Failed to generate preview: ' + result.error, 'error');
    }
}

// Save Current Document
async function saveCurrentDocument() {
    const title = document.getElementById('doc-title').value.trim();
    const id = document.getElementById('doc-id').value.trim();
    const version = document.getElementById('doc-version').value.trim();
    const updated = document.getElementById('doc-updated').value;
    const description = document.getElementById('doc-description').value.trim();
    const cardImage = document.getElementById('doc-card-image').value.trim();
    
    if (!title || !id) {
        showToast('Document title and ID are required', 'error');
        return;
    }
    
    // Check for duplicate IDs
    const duplicateId = AppState.data.documents.find(doc => 
        doc.id === id && doc !== AppState.currentDocument
    );
    
    if (duplicateId) {
        showToast('A document with this ID already exists', 'error');
        return;
    }
    
    // Update current document
    AppState.currentDocument.title = title;
    AppState.currentDocument.id = id;
    AppState.currentDocument.version = version;
    AppState.currentDocument.lastUpdated = updated;
    AppState.currentDocument.description = description;
    AppState.currentDocument.cardImage = cardImage;
    
    // Auto-save to project
    const saved = await saveProjectData();
    if (saved) {
        renderDocumentsList();
        showToast('Document saved', 'success');
    }
}

// Delete Current Document
async function deleteCurrentDocument() {
    if (!confirm('Are you sure you want to delete this document? This cannot be undone.')) {
        return;
    }
    
    const index = AppState.data.documents.findIndex(doc => doc === AppState.currentDocument);
    if (index > -1) {
        AppState.data.documents.splice(index, 1);
        AppState.currentDocument = null;
        
        // Auto-save to project
        await saveProjectData();
        
        renderDocumentsList();
        renderDocumentEditor();
        showToast('Document deleted', 'success');
    }
}

// Auto-generate Document ID
function autoGenerateDocId() {
    const title = document.getElementById('doc-title').value.trim();
    const currentId = document.getElementById('doc-id').value.trim();
    
    // Only auto-generate if ID is empty or is a default generated one
    if (!currentId || currentId.startsWith('new-document-')) {
        const generatedId = title
            .toLowerCase()
            .replace(/[^a-z0-9\s-]/g, '')
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-')
            .replace(/^-|-$/g, '');
        
        document.getElementById('doc-id').value = generatedId;
    }
}

// Select Card Image
async function selectCardImage() {
    if (!AppState.currentProjectName || !AppState.currentDocument) {
        showToast('Please save the document first', 'error');
        return;
    }
    
    const result = await window.electronAPI.selectFile({
        filters: [
            { name: 'Images', extensions: ['png', 'jpg', 'jpeg', 'svg', 'gif'] }
        ]
    });
    
    if (result.success) {
        const filename = result.path.split('/').pop();
        const docId = document.getElementById('doc-id').value.trim() || AppState.currentDocument.id;
        const relativePath = `images/${docId}/${filename}`;
        
        // Copy file to project
        const copyResult = await window.electronAPI.copyFileToProject(
            AppState.currentProjectName,
            result.path,
            relativePath
        );
        
        if (copyResult.success) {
            // Use project-relative path (images/, not assets/images/)
            document.getElementById('doc-card-image').value = `images/${docId}/${filename}`;
            showToast('Image copied to project!', 'success');
        } else {
            showToast('Failed to copy image: ' + copyResult.error, 'error');
        }
    }
}

// Select Section Image
async function selectSectionImage() {
    if (!AppState.currentProjectName || !AppState.currentDocument) {
        showToast('Please save the document first', 'error');
        return;
    }
    
    const result = await window.electronAPI.selectFile({
        filters: [
            { name: 'Images', extensions: ['png', 'jpg', 'jpeg', 'svg', 'gif'] }
        ]
    });
    
    if (result.success) {
        const filename = result.path.split('/').pop();
        const docId = AppState.currentDocument.id;
        const relativePath = `images/${docId}/${filename}`;
        
        // Copy file to project
        const copyResult = await window.electronAPI.copyFileToProject(
            AppState.currentProjectName,
            result.path,
            relativePath
        );
        
        if (copyResult.success) {
            // Use project-relative path (images/, not assets/images/)
            document.getElementById('section-image').value = `images/${docId}/${filename}`;
            showToast('Image copied to project!', 'success');
        } else {
            showToast('Failed to copy image: ' + copyResult.error, 'error');
        }
    }
}

// Toast Notification
function showToast(message, type = 'info') {
    const toast = document.getElementById('toast');
    toast.textContent = message;
    toast.className = 'toast ' + type;
    toast.style.display = 'block';
    
    setTimeout(() => {
        toast.style.display = 'none';
    }, 3000);
}

